config/routes.rb
Rails.application.routes.draw do
  resources :publications
  devise_for :users
  root to: 'publications#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'

  validates :title, presence: true

  def categories
    category.split(',')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :clear_flashes

  def clear_flashes
    flash[:notice] = flash[:alert] = []
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    render html: '<h1>Pages index</h1>'
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
    @publications = Publication.all
  end

  def show; end

  def new
    @publication = Publication.new
  end

  def edit; end

  def create
    @publication = Publication.new(publication_params.merge(author_id: current_user.id))

    if @publication.save
      redirect_to publications_path, notice: 'Publication was successfully created.'
    else
      flash[:alert] = @publication.errors.full_messages
      render :new
    end
  end

  def update
    if @publication.update(publication_params)
      redirect_to publications_path
    else
      render :edit
    end
  end

  def destroy
    @publication.destroy
    redirect_to publications_url, notice: 'Publication was successfully destroyed.'
  end

  private

  def set_publication
    @publication = Publication.find(params[:id])
  end

  def publication_params
    params.require(:publication).permit(:title, :abstract, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  </head>

  <body>
    <ul class="nav justify-content-end mr-2 mb-3 mt-3">

      <li class="nav-item">
        <a class="nav-link" href="<%= publications_path %>">Publications</a>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'btn btn-outline-info'%>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class:'btn btn-outline-info'%>
        <% end %>
      </li>
    </ul>
    <% flash[:notice].each do |notice| %>
    <p class=" alert alert-success"><%= notice %></p>
    <div class="alert notice alert-success alert-dismissible fade show" role="alert">
        <strong><%= alert %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% flash[:alert].each do |alert| %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong><%= alert %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true, class:'form-group') do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label :abstract %>
    <%= form.text_area :abstract, class:'form-control', rows: 10 %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_area :category, class:'form-control', rows: 3 %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Changes', class:'btn btn-success' %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<h3>Publications</h3>
  <% if user_signed_in? %>
    <%= link_to 'New Publication', new_publication_path, class:'btn btn-primary btn-sm text-white' %><br/><br/>
  <% end %>
  <% @publications.each do |publication| %>

    <div class="card mt-3">
      <div class="card-body">
        <%= link_to publication, class:'text-primary' do %>
          <h5 class="card-title"><%= publication.title %></h5>
        <% end %>

        <h6 class="card-subtitle mb-2 text-muted"><%= publication.categories.join(' ') %></h6>

        <% publication.abstract.split("\r\n").each do |para| %>
          <p class="card-text">
            <%= para %>
          </p>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to 'Edit', edit_publication_path(publication) %>
          <%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %>
          <br/><br/>
        <% end %>

      </div>
    </div>

  <% end %>
<br>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @publication.title %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @publication.abstract %>
</p>

<p>
  <strong>Category:</strong>
  <%= @publication.category %>
</p>

<p>
  <strong>Author:</strong>
  <%= @publication.author_id %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>